// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: proto/cards.proto

package pbconnect

import (
	pb "backend_nonsense/pb"
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// MTGRPCName is the fully-qualified name of the MTGRPC service.
	MTGRPCName = "cards.MTGRPC"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// MTGRPCGetCardProcedure is the fully-qualified name of the MTGRPC's GetCard RPC.
	MTGRPCGetCardProcedure = "/cards.MTGRPC/GetCard"
	// MTGRPCSearchCardsProcedure is the fully-qualified name of the MTGRPC's SearchCards RPC.
	MTGRPCSearchCardsProcedure = "/cards.MTGRPC/SearchCards"
	// MTGRPCListCardsProcedure is the fully-qualified name of the MTGRPC's ListCards RPC.
	MTGRPCListCardsProcedure = "/cards.MTGRPC/ListCards"
	// MTGRPCListSetsProcedure is the fully-qualified name of the MTGRPC's ListSets RPC.
	MTGRPCListSetsProcedure = "/cards.MTGRPC/ListSets"
	// MTGRPCGetSetInfoProcedure is the fully-qualified name of the MTGRPC's GetSetInfo RPC.
	MTGRPCGetSetInfoProcedure = "/cards.MTGRPC/GetSetInfo"
)

// MTGRPCClient is a client for the cards.MTGRPC service.
type MTGRPCClient interface {
	GetCard(context.Context, *connect.Request[pb.GetCardRequest]) (*connect.Response[pb.GetCardResponse], error)
	SearchCards(context.Context, *connect.Request[pb.SearchCardsRequest]) (*connect.Response[pb.SearchCardsResponse], error)
	ListCards(context.Context, *connect.Request[pb.ListCardsRequest]) (*connect.Response[pb.ListCardsResponse], error)
	ListSets(context.Context, *connect.Request[pb.ListSetsRequest]) (*connect.Response[pb.ListSetsResponse], error)
	GetSetInfo(context.Context, *connect.Request[pb.GetSetInfoRequest]) (*connect.Response[pb.GetSetInfoResponse], error)
}

// NewMTGRPCClient constructs a client for the cards.MTGRPC service. By default, it uses the Connect
// protocol with the binary Protobuf Codec, asks for gzipped responses, and sends uncompressed
// requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewMTGRPCClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) MTGRPCClient {
	baseURL = strings.TrimRight(baseURL, "/")
	mTGRPCMethods := pb.File_proto_cards_proto.Services().ByName("MTGRPC").Methods()
	return &mTGRPCClient{
		getCard: connect.NewClient[pb.GetCardRequest, pb.GetCardResponse](
			httpClient,
			baseURL+MTGRPCGetCardProcedure,
			connect.WithSchema(mTGRPCMethods.ByName("GetCard")),
			connect.WithClientOptions(opts...),
		),
		searchCards: connect.NewClient[pb.SearchCardsRequest, pb.SearchCardsResponse](
			httpClient,
			baseURL+MTGRPCSearchCardsProcedure,
			connect.WithSchema(mTGRPCMethods.ByName("SearchCards")),
			connect.WithClientOptions(opts...),
		),
		listCards: connect.NewClient[pb.ListCardsRequest, pb.ListCardsResponse](
			httpClient,
			baseURL+MTGRPCListCardsProcedure,
			connect.WithSchema(mTGRPCMethods.ByName("ListCards")),
			connect.WithClientOptions(opts...),
		),
		listSets: connect.NewClient[pb.ListSetsRequest, pb.ListSetsResponse](
			httpClient,
			baseURL+MTGRPCListSetsProcedure,
			connect.WithSchema(mTGRPCMethods.ByName("ListSets")),
			connect.WithClientOptions(opts...),
		),
		getSetInfo: connect.NewClient[pb.GetSetInfoRequest, pb.GetSetInfoResponse](
			httpClient,
			baseURL+MTGRPCGetSetInfoProcedure,
			connect.WithSchema(mTGRPCMethods.ByName("GetSetInfo")),
			connect.WithClientOptions(opts...),
		),
	}
}

// mTGRPCClient implements MTGRPCClient.
type mTGRPCClient struct {
	getCard     *connect.Client[pb.GetCardRequest, pb.GetCardResponse]
	searchCards *connect.Client[pb.SearchCardsRequest, pb.SearchCardsResponse]
	listCards   *connect.Client[pb.ListCardsRequest, pb.ListCardsResponse]
	listSets    *connect.Client[pb.ListSetsRequest, pb.ListSetsResponse]
	getSetInfo  *connect.Client[pb.GetSetInfoRequest, pb.GetSetInfoResponse]
}

// GetCard calls cards.MTGRPC.GetCard.
func (c *mTGRPCClient) GetCard(ctx context.Context, req *connect.Request[pb.GetCardRequest]) (*connect.Response[pb.GetCardResponse], error) {
	return c.getCard.CallUnary(ctx, req)
}

// SearchCards calls cards.MTGRPC.SearchCards.
func (c *mTGRPCClient) SearchCards(ctx context.Context, req *connect.Request[pb.SearchCardsRequest]) (*connect.Response[pb.SearchCardsResponse], error) {
	return c.searchCards.CallUnary(ctx, req)
}

// ListCards calls cards.MTGRPC.ListCards.
func (c *mTGRPCClient) ListCards(ctx context.Context, req *connect.Request[pb.ListCardsRequest]) (*connect.Response[pb.ListCardsResponse], error) {
	return c.listCards.CallUnary(ctx, req)
}

// ListSets calls cards.MTGRPC.ListSets.
func (c *mTGRPCClient) ListSets(ctx context.Context, req *connect.Request[pb.ListSetsRequest]) (*connect.Response[pb.ListSetsResponse], error) {
	return c.listSets.CallUnary(ctx, req)
}

// GetSetInfo calls cards.MTGRPC.GetSetInfo.
func (c *mTGRPCClient) GetSetInfo(ctx context.Context, req *connect.Request[pb.GetSetInfoRequest]) (*connect.Response[pb.GetSetInfoResponse], error) {
	return c.getSetInfo.CallUnary(ctx, req)
}

// MTGRPCHandler is an implementation of the cards.MTGRPC service.
type MTGRPCHandler interface {
	GetCard(context.Context, *connect.Request[pb.GetCardRequest]) (*connect.Response[pb.GetCardResponse], error)
	SearchCards(context.Context, *connect.Request[pb.SearchCardsRequest]) (*connect.Response[pb.SearchCardsResponse], error)
	ListCards(context.Context, *connect.Request[pb.ListCardsRequest]) (*connect.Response[pb.ListCardsResponse], error)
	ListSets(context.Context, *connect.Request[pb.ListSetsRequest]) (*connect.Response[pb.ListSetsResponse], error)
	GetSetInfo(context.Context, *connect.Request[pb.GetSetInfoRequest]) (*connect.Response[pb.GetSetInfoResponse], error)
}

// NewMTGRPCHandler builds an HTTP handler from the service implementation. It returns the path on
// which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewMTGRPCHandler(svc MTGRPCHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	mTGRPCMethods := pb.File_proto_cards_proto.Services().ByName("MTGRPC").Methods()
	mTGRPCGetCardHandler := connect.NewUnaryHandler(
		MTGRPCGetCardProcedure,
		svc.GetCard,
		connect.WithSchema(mTGRPCMethods.ByName("GetCard")),
		connect.WithHandlerOptions(opts...),
	)
	mTGRPCSearchCardsHandler := connect.NewUnaryHandler(
		MTGRPCSearchCardsProcedure,
		svc.SearchCards,
		connect.WithSchema(mTGRPCMethods.ByName("SearchCards")),
		connect.WithHandlerOptions(opts...),
	)
	mTGRPCListCardsHandler := connect.NewUnaryHandler(
		MTGRPCListCardsProcedure,
		svc.ListCards,
		connect.WithSchema(mTGRPCMethods.ByName("ListCards")),
		connect.WithHandlerOptions(opts...),
	)
	mTGRPCListSetsHandler := connect.NewUnaryHandler(
		MTGRPCListSetsProcedure,
		svc.ListSets,
		connect.WithSchema(mTGRPCMethods.ByName("ListSets")),
		connect.WithHandlerOptions(opts...),
	)
	mTGRPCGetSetInfoHandler := connect.NewUnaryHandler(
		MTGRPCGetSetInfoProcedure,
		svc.GetSetInfo,
		connect.WithSchema(mTGRPCMethods.ByName("GetSetInfo")),
		connect.WithHandlerOptions(opts...),
	)
	return "/cards.MTGRPC/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case MTGRPCGetCardProcedure:
			mTGRPCGetCardHandler.ServeHTTP(w, r)
		case MTGRPCSearchCardsProcedure:
			mTGRPCSearchCardsHandler.ServeHTTP(w, r)
		case MTGRPCListCardsProcedure:
			mTGRPCListCardsHandler.ServeHTTP(w, r)
		case MTGRPCListSetsProcedure:
			mTGRPCListSetsHandler.ServeHTTP(w, r)
		case MTGRPCGetSetInfoProcedure:
			mTGRPCGetSetInfoHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedMTGRPCHandler returns CodeUnimplemented from all methods.
type UnimplementedMTGRPCHandler struct{}

func (UnimplementedMTGRPCHandler) GetCard(context.Context, *connect.Request[pb.GetCardRequest]) (*connect.Response[pb.GetCardResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cards.MTGRPC.GetCard is not implemented"))
}

func (UnimplementedMTGRPCHandler) SearchCards(context.Context, *connect.Request[pb.SearchCardsRequest]) (*connect.Response[pb.SearchCardsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cards.MTGRPC.SearchCards is not implemented"))
}

func (UnimplementedMTGRPCHandler) ListCards(context.Context, *connect.Request[pb.ListCardsRequest]) (*connect.Response[pb.ListCardsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cards.MTGRPC.ListCards is not implemented"))
}

func (UnimplementedMTGRPCHandler) ListSets(context.Context, *connect.Request[pb.ListSetsRequest]) (*connect.Response[pb.ListSetsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cards.MTGRPC.ListSets is not implemented"))
}

func (UnimplementedMTGRPCHandler) GetSetInfo(context.Context, *connect.Request[pb.GetSetInfoRequest]) (*connect.Response[pb.GetSetInfoResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cards.MTGRPC.GetSetInfo is not implemented"))
}
