// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/cards.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Prices message
type Prices struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Usd           string                 `protobuf:"bytes,1,opt,name=usd,proto3" json:"usd,omitempty"`
	UsdFoil       string                 `protobuf:"bytes,2,opt,name=usd_foil,json=usdFoil,proto3" json:"usd_foil,omitempty"`
	Eur           string                 `protobuf:"bytes,3,opt,name=eur,proto3" json:"eur,omitempty"`
	EurFoil       string                 `protobuf:"bytes,4,opt,name=eur_foil,json=eurFoil,proto3" json:"eur_foil,omitempty"`
	Tix           string                 `protobuf:"bytes,5,opt,name=tix,proto3" json:"tix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Prices) Reset() {
	*x = Prices{}
	mi := &file_proto_cards_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Prices) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Prices) ProtoMessage() {}

func (x *Prices) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cards_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Prices.ProtoReflect.Descriptor instead.
func (*Prices) Descriptor() ([]byte, []int) {
	return file_proto_cards_proto_rawDescGZIP(), []int{0}
}

func (x *Prices) GetUsd() string {
	if x != nil {
		return x.Usd
	}
	return ""
}

func (x *Prices) GetUsdFoil() string {
	if x != nil {
		return x.UsdFoil
	}
	return ""
}

func (x *Prices) GetEur() string {
	if x != nil {
		return x.Eur
	}
	return ""
}

func (x *Prices) GetEurFoil() string {
	if x != nil {
		return x.EurFoil
	}
	return ""
}

func (x *Prices) GetTix() string {
	if x != nil {
		return x.Tix
	}
	return ""
}

// Shared card message
type Card struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Set           string                 `protobuf:"bytes,2,opt,name=set,proto3" json:"set,omitempty"`
	Number        string                 `protobuf:"bytes,3,opt,name=number,proto3" json:"number,omitempty"`
	Count         int32                  `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,5,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	Prices        *Prices                `protobuf:"bytes,6,opt,name=prices,proto3" json:"prices,omitempty"`
	Colors        []string               `protobuf:"bytes,7,rep,name=colors,proto3" json:"colors,omitempty"`
	Rarity        string                 `protobuf:"bytes,8,opt,name=rarity,proto3" json:"rarity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Card) Reset() {
	*x = Card{}
	mi := &file_proto_cards_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Card) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Card) ProtoMessage() {}

func (x *Card) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cards_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Card.ProtoReflect.Descriptor instead.
func (*Card) Descriptor() ([]byte, []int) {
	return file_proto_cards_proto_rawDescGZIP(), []int{1}
}

func (x *Card) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Card) GetSet() string {
	if x != nil {
		return x.Set
	}
	return ""
}

func (x *Card) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

func (x *Card) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *Card) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *Card) GetPrices() *Prices {
	if x != nil {
		return x.Prices
	}
	return nil
}

func (x *Card) GetColors() []string {
	if x != nil {
		return x.Colors
	}
	return nil
}

func (x *Card) GetRarity() string {
	if x != nil {
		return x.Rarity
	}
	return ""
}

// AddCard
type AddCardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Set           string                 `protobuf:"bytes,2,opt,name=set,proto3" json:"set,omitempty"`
	Number        string                 `protobuf:"bytes,3,opt,name=number,proto3" json:"number,omitempty"`
	Count         int32                  `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddCardRequest) Reset() {
	*x = AddCardRequest{}
	mi := &file_proto_cards_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCardRequest) ProtoMessage() {}

func (x *AddCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cards_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCardRequest.ProtoReflect.Descriptor instead.
func (*AddCardRequest) Descriptor() ([]byte, []int) {
	return file_proto_cards_proto_rawDescGZIP(), []int{2}
}

func (x *AddCardRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddCardRequest) GetSet() string {
	if x != nil {
		return x.Set
	}
	return ""
}

func (x *AddCardRequest) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

func (x *AddCardRequest) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type AddCardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Card          *Card                  `protobuf:"bytes,1,opt,name=card,proto3" json:"card,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddCardResponse) Reset() {
	*x = AddCardResponse{}
	mi := &file_proto_cards_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddCardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCardResponse) ProtoMessage() {}

func (x *AddCardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cards_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCardResponse.ProtoReflect.Descriptor instead.
func (*AddCardResponse) Descriptor() ([]byte, []int) {
	return file_proto_cards_proto_rawDescGZIP(), []int{3}
}

func (x *AddCardResponse) GetCard() *Card {
	if x != nil {
		return x.Card
	}
	return nil
}

// GetCard — exact lookup by name + set + number
type GetCardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Set           string                 `protobuf:"bytes,2,opt,name=set,proto3" json:"set,omitempty"`
	Number        string                 `protobuf:"bytes,3,opt,name=number,proto3" json:"number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCardRequest) Reset() {
	*x = GetCardRequest{}
	mi := &file_proto_cards_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCardRequest) ProtoMessage() {}

func (x *GetCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cards_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCardRequest.ProtoReflect.Descriptor instead.
func (*GetCardRequest) Descriptor() ([]byte, []int) {
	return file_proto_cards_proto_rawDescGZIP(), []int{4}
}

func (x *GetCardRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetCardRequest) GetSet() string {
	if x != nil {
		return x.Set
	}
	return ""
}

func (x *GetCardRequest) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

type GetCardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Card          *Card                  `protobuf:"bytes,1,opt,name=card,proto3" json:"card,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCardResponse) Reset() {
	*x = GetCardResponse{}
	mi := &file_proto_cards_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCardResponse) ProtoMessage() {}

func (x *GetCardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cards_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCardResponse.ProtoReflect.Descriptor instead.
func (*GetCardResponse) Descriptor() ([]byte, []int) {
	return file_proto_cards_proto_rawDescGZIP(), []int{5}
}

func (x *GetCardResponse) GetCard() *Card {
	if x != nil {
		return x.Card
	}
	return nil
}

// GetCardsByName — all printings of a card across sets
type GetCardsByNameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCardsByNameRequest) Reset() {
	*x = GetCardsByNameRequest{}
	mi := &file_proto_cards_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCardsByNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCardsByNameRequest) ProtoMessage() {}

func (x *GetCardsByNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cards_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCardsByNameRequest.ProtoReflect.Descriptor instead.
func (*GetCardsByNameRequest) Descriptor() ([]byte, []int) {
	return file_proto_cards_proto_rawDescGZIP(), []int{6}
}

func (x *GetCardsByNameRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetCardsByNameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cards         []*Card                `protobuf:"bytes,1,rep,name=cards,proto3" json:"cards,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCardsByNameResponse) Reset() {
	*x = GetCardsByNameResponse{}
	mi := &file_proto_cards_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCardsByNameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCardsByNameResponse) ProtoMessage() {}

func (x *GetCardsByNameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cards_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCardsByNameResponse.ProtoReflect.Descriptor instead.
func (*GetCardsByNameResponse) Descriptor() ([]byte, []int) {
	return file_proto_cards_proto_rawDescGZIP(), []int{7}
}

func (x *GetCardsByNameResponse) GetCards() []*Card {
	if x != nil {
		return x.Cards
	}
	return nil
}

// GetCardsBySet — all cards in a given set
type GetCardsBySetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Set           string                 `protobuf:"bytes,1,opt,name=set,proto3" json:"set,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCardsBySetRequest) Reset() {
	*x = GetCardsBySetRequest{}
	mi := &file_proto_cards_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCardsBySetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCardsBySetRequest) ProtoMessage() {}

func (x *GetCardsBySetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cards_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCardsBySetRequest.ProtoReflect.Descriptor instead.
func (*GetCardsBySetRequest) Descriptor() ([]byte, []int) {
	return file_proto_cards_proto_rawDescGZIP(), []int{8}
}

func (x *GetCardsBySetRequest) GetSet() string {
	if x != nil {
		return x.Set
	}
	return ""
}

func (x *GetCardsBySetRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetCardsBySetRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type GetCardsBySetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cards         []*Card                `protobuf:"bytes,1,rep,name=cards,proto3" json:"cards,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCardsBySetResponse) Reset() {
	*x = GetCardsBySetResponse{}
	mi := &file_proto_cards_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCardsBySetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCardsBySetResponse) ProtoMessage() {}

func (x *GetCardsBySetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cards_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCardsBySetResponse.ProtoReflect.Descriptor instead.
func (*GetCardsBySetResponse) Descriptor() ([]byte, []int) {
	return file_proto_cards_proto_rawDescGZIP(), []int{9}
}

func (x *GetCardsBySetResponse) GetCards() []*Card {
	if x != nil {
		return x.Cards
	}
	return nil
}

func (x *GetCardsBySetResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

// SearchCards — flexible filter, all fields optional
type SearchCardsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Set           string                 `protobuf:"bytes,2,opt,name=set,proto3" json:"set,omitempty"`
	Colors        []string               `protobuf:"bytes,3,rep,name=colors,proto3" json:"colors,omitempty"` // e.g. ["W", "U", "B", "R", "G"]
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,5,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	Rarity        []string               `protobuf:"bytes,6,rep,name=rarity,proto3" json:"rarity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchCardsRequest) Reset() {
	*x = SearchCardsRequest{}
	mi := &file_proto_cards_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchCardsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchCardsRequest) ProtoMessage() {}

func (x *SearchCardsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cards_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchCardsRequest.ProtoReflect.Descriptor instead.
func (*SearchCardsRequest) Descriptor() ([]byte, []int) {
	return file_proto_cards_proto_rawDescGZIP(), []int{10}
}

func (x *SearchCardsRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SearchCardsRequest) GetSet() string {
	if x != nil {
		return x.Set
	}
	return ""
}

func (x *SearchCardsRequest) GetColors() []string {
	if x != nil {
		return x.Colors
	}
	return nil
}

func (x *SearchCardsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *SearchCardsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *SearchCardsRequest) GetRarity() []string {
	if x != nil {
		return x.Rarity
	}
	return nil
}

type SearchCardsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cards         []*Card                `protobuf:"bytes,1,rep,name=cards,proto3" json:"cards,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchCardsResponse) Reset() {
	*x = SearchCardsResponse{}
	mi := &file_proto_cards_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchCardsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchCardsResponse) ProtoMessage() {}

func (x *SearchCardsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cards_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchCardsResponse.ProtoReflect.Descriptor instead.
func (*SearchCardsResponse) Descriptor() ([]byte, []int) {
	return file_proto_cards_proto_rawDescGZIP(), []int{11}
}

func (x *SearchCardsResponse) GetCards() []*Card {
	if x != nil {
		return x.Cards
	}
	return nil
}

func (x *SearchCardsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

// ListCards — full collection with optional pagination
type ListCardsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      int32                  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCardsRequest) Reset() {
	*x = ListCardsRequest{}
	mi := &file_proto_cards_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCardsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCardsRequest) ProtoMessage() {}

func (x *ListCardsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cards_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCardsRequest.ProtoReflect.Descriptor instead.
func (*ListCardsRequest) Descriptor() ([]byte, []int) {
	return file_proto_cards_proto_rawDescGZIP(), []int{12}
}

func (x *ListCardsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListCardsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListCardsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cards         []*Card                `protobuf:"bytes,1,rep,name=cards,proto3" json:"cards,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCardsResponse) Reset() {
	*x = ListCardsResponse{}
	mi := &file_proto_cards_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCardsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCardsResponse) ProtoMessage() {}

func (x *ListCardsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cards_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCardsResponse.ProtoReflect.Descriptor instead.
func (*ListCardsResponse) Descriptor() ([]byte, []int) {
	return file_proto_cards_proto_rawDescGZIP(), []int{13}
}

func (x *ListCardsResponse) GetCards() []*Card {
	if x != nil {
		return x.Cards
	}
	return nil
}

func (x *ListCardsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

var File_proto_cards_proto protoreflect.FileDescriptor

const file_proto_cards_proto_rawDesc = "" +
	"\n" +
	"\x11proto/cards.proto\x12\x05cards\"t\n" +
	"\x06Prices\x12\x10\n" +
	"\x03usd\x18\x01 \x01(\tR\x03usd\x12\x19\n" +
	"\busd_foil\x18\x02 \x01(\tR\ausdFoil\x12\x10\n" +
	"\x03eur\x18\x03 \x01(\tR\x03eur\x12\x19\n" +
	"\beur_foil\x18\x04 \x01(\tR\aeurFoil\x12\x10\n" +
	"\x03tix\x18\x05 \x01(\tR\x03tix\"\xce\x01\n" +
	"\x04Card\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03set\x18\x02 \x01(\tR\x03set\x12\x16\n" +
	"\x06number\x18\x03 \x01(\tR\x06number\x12\x14\n" +
	"\x05count\x18\x04 \x01(\x05R\x05count\x12\x1b\n" +
	"\timage_url\x18\x05 \x01(\tR\bimageUrl\x12%\n" +
	"\x06prices\x18\x06 \x01(\v2\r.cards.PricesR\x06prices\x12\x16\n" +
	"\x06colors\x18\a \x03(\tR\x06colors\x12\x16\n" +
	"\x06rarity\x18\b \x01(\tR\x06rarity\"d\n" +
	"\x0eAddCardRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03set\x18\x02 \x01(\tR\x03set\x12\x16\n" +
	"\x06number\x18\x03 \x01(\tR\x06number\x12\x14\n" +
	"\x05count\x18\x04 \x01(\x05R\x05count\"2\n" +
	"\x0fAddCardResponse\x12\x1f\n" +
	"\x04card\x18\x01 \x01(\v2\v.cards.CardR\x04card\"N\n" +
	"\x0eGetCardRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03set\x18\x02 \x01(\tR\x03set\x12\x16\n" +
	"\x06number\x18\x03 \x01(\tR\x06number\"2\n" +
	"\x0fGetCardResponse\x12\x1f\n" +
	"\x04card\x18\x01 \x01(\v2\v.cards.CardR\x04card\"+\n" +
	"\x15GetCardsByNameRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\";\n" +
	"\x16GetCardsByNameResponse\x12!\n" +
	"\x05cards\x18\x01 \x03(\v2\v.cards.CardR\x05cards\"d\n" +
	"\x14GetCardsBySetRequest\x12\x10\n" +
	"\x03set\x18\x01 \x01(\tR\x03set\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\"b\n" +
	"\x15GetCardsBySetResponse\x12!\n" +
	"\x05cards\x18\x01 \x03(\v2\v.cards.CardR\x05cards\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"\xa6\x01\n" +
	"\x12SearchCardsRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03set\x18\x02 \x01(\tR\x03set\x12\x16\n" +
	"\x06colors\x18\x03 \x03(\tR\x06colors\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x05 \x01(\tR\tpageToken\x12\x16\n" +
	"\x06rarity\x18\x06 \x03(\tR\x06rarity\"`\n" +
	"\x13SearchCardsResponse\x12!\n" +
	"\x05cards\x18\x01 \x03(\v2\v.cards.CardR\x05cards\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"N\n" +
	"\x10ListCardsRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\"^\n" +
	"\x11ListCardsResponse\x12!\n" +
	"\x05cards\x18\x01 \x03(\v2\v.cards.CardR\x05cards\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken2\xa9\x03\n" +
	"\x06MTGRPC\x12:\n" +
	"\aAddCard\x12\x15.cards.AddCardRequest\x1a\x16.cards.AddCardResponse\"\x00\x12:\n" +
	"\aGetCard\x12\x15.cards.GetCardRequest\x1a\x16.cards.GetCardResponse\"\x00\x12O\n" +
	"\x0eGetCardsByName\x12\x1c.cards.GetCardsByNameRequest\x1a\x1d.cards.GetCardsByNameResponse\"\x00\x12L\n" +
	"\rGetCardsBySet\x12\x1b.cards.GetCardsBySetRequest\x1a\x1c.cards.GetCardsBySetResponse\"\x00\x12F\n" +
	"\vSearchCards\x12\x19.cards.SearchCardsRequest\x1a\x1a.cards.SearchCardsResponse\"\x00\x12@\n" +
	"\tListCards\x12\x17.cards.ListCardsRequest\x1a\x18.cards.ListCardsResponse\"\x00B\x15Z\x13backend_nonsense/pbb\x06proto3"

var (
	file_proto_cards_proto_rawDescOnce sync.Once
	file_proto_cards_proto_rawDescData []byte
)

func file_proto_cards_proto_rawDescGZIP() []byte {
	file_proto_cards_proto_rawDescOnce.Do(func() {
		file_proto_cards_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_cards_proto_rawDesc), len(file_proto_cards_proto_rawDesc)))
	})
	return file_proto_cards_proto_rawDescData
}

var file_proto_cards_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_proto_cards_proto_goTypes = []any{
	(*Prices)(nil),                 // 0: cards.Prices
	(*Card)(nil),                   // 1: cards.Card
	(*AddCardRequest)(nil),         // 2: cards.AddCardRequest
	(*AddCardResponse)(nil),        // 3: cards.AddCardResponse
	(*GetCardRequest)(nil),         // 4: cards.GetCardRequest
	(*GetCardResponse)(nil),        // 5: cards.GetCardResponse
	(*GetCardsByNameRequest)(nil),  // 6: cards.GetCardsByNameRequest
	(*GetCardsByNameResponse)(nil), // 7: cards.GetCardsByNameResponse
	(*GetCardsBySetRequest)(nil),   // 8: cards.GetCardsBySetRequest
	(*GetCardsBySetResponse)(nil),  // 9: cards.GetCardsBySetResponse
	(*SearchCardsRequest)(nil),     // 10: cards.SearchCardsRequest
	(*SearchCardsResponse)(nil),    // 11: cards.SearchCardsResponse
	(*ListCardsRequest)(nil),       // 12: cards.ListCardsRequest
	(*ListCardsResponse)(nil),      // 13: cards.ListCardsResponse
}
var file_proto_cards_proto_depIdxs = []int32{
	0,  // 0: cards.Card.prices:type_name -> cards.Prices
	1,  // 1: cards.AddCardResponse.card:type_name -> cards.Card
	1,  // 2: cards.GetCardResponse.card:type_name -> cards.Card
	1,  // 3: cards.GetCardsByNameResponse.cards:type_name -> cards.Card
	1,  // 4: cards.GetCardsBySetResponse.cards:type_name -> cards.Card
	1,  // 5: cards.SearchCardsResponse.cards:type_name -> cards.Card
	1,  // 6: cards.ListCardsResponse.cards:type_name -> cards.Card
	2,  // 7: cards.MTGRPC.AddCard:input_type -> cards.AddCardRequest
	4,  // 8: cards.MTGRPC.GetCard:input_type -> cards.GetCardRequest
	6,  // 9: cards.MTGRPC.GetCardsByName:input_type -> cards.GetCardsByNameRequest
	8,  // 10: cards.MTGRPC.GetCardsBySet:input_type -> cards.GetCardsBySetRequest
	10, // 11: cards.MTGRPC.SearchCards:input_type -> cards.SearchCardsRequest
	12, // 12: cards.MTGRPC.ListCards:input_type -> cards.ListCardsRequest
	3,  // 13: cards.MTGRPC.AddCard:output_type -> cards.AddCardResponse
	5,  // 14: cards.MTGRPC.GetCard:output_type -> cards.GetCardResponse
	7,  // 15: cards.MTGRPC.GetCardsByName:output_type -> cards.GetCardsByNameResponse
	9,  // 16: cards.MTGRPC.GetCardsBySet:output_type -> cards.GetCardsBySetResponse
	11, // 17: cards.MTGRPC.SearchCards:output_type -> cards.SearchCardsResponse
	13, // 18: cards.MTGRPC.ListCards:output_type -> cards.ListCardsResponse
	13, // [13:19] is the sub-list for method output_type
	7,  // [7:13] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_proto_cards_proto_init() }
func file_proto_cards_proto_init() {
	if File_proto_cards_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_cards_proto_rawDesc), len(file_proto_cards_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_cards_proto_goTypes,
		DependencyIndexes: file_proto_cards_proto_depIdxs,
		MessageInfos:      file_proto_cards_proto_msgTypes,
	}.Build()
	File_proto_cards_proto = out.File
	file_proto_cards_proto_goTypes = nil
	file_proto_cards_proto_depIdxs = nil
}
