// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: proto/cards.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MTGRPC_GetCard_FullMethodName     = "/cards.MTGRPC/GetCard"
	MTGRPC_SearchCards_FullMethodName = "/cards.MTGRPC/SearchCards"
	MTGRPC_ListCards_FullMethodName   = "/cards.MTGRPC/ListCards"
	MTGRPC_ListSets_FullMethodName    = "/cards.MTGRPC/ListSets"
)

// MTGRPCClient is the client API for MTGRPC service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MTGRPCClient interface {
	GetCard(ctx context.Context, in *GetCardRequest, opts ...grpc.CallOption) (*GetCardResponse, error)
	SearchCards(ctx context.Context, in *SearchCardsRequest, opts ...grpc.CallOption) (*SearchCardsResponse, error)
	ListCards(ctx context.Context, in *ListCardsRequest, opts ...grpc.CallOption) (*ListCardsResponse, error)
	ListSets(ctx context.Context, in *ListSetsRequest, opts ...grpc.CallOption) (*ListSetsResponse, error)
}

type mTGRPCClient struct {
	cc grpc.ClientConnInterface
}

func NewMTGRPCClient(cc grpc.ClientConnInterface) MTGRPCClient {
	return &mTGRPCClient{cc}
}

func (c *mTGRPCClient) GetCard(ctx context.Context, in *GetCardRequest, opts ...grpc.CallOption) (*GetCardResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCardResponse)
	err := c.cc.Invoke(ctx, MTGRPC_GetCard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mTGRPCClient) SearchCards(ctx context.Context, in *SearchCardsRequest, opts ...grpc.CallOption) (*SearchCardsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchCardsResponse)
	err := c.cc.Invoke(ctx, MTGRPC_SearchCards_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mTGRPCClient) ListCards(ctx context.Context, in *ListCardsRequest, opts ...grpc.CallOption) (*ListCardsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCardsResponse)
	err := c.cc.Invoke(ctx, MTGRPC_ListCards_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mTGRPCClient) ListSets(ctx context.Context, in *ListSetsRequest, opts ...grpc.CallOption) (*ListSetsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSetsResponse)
	err := c.cc.Invoke(ctx, MTGRPC_ListSets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MTGRPCServer is the server API for MTGRPC service.
// All implementations must embed UnimplementedMTGRPCServer
// for forward compatibility.
type MTGRPCServer interface {
	GetCard(context.Context, *GetCardRequest) (*GetCardResponse, error)
	SearchCards(context.Context, *SearchCardsRequest) (*SearchCardsResponse, error)
	ListCards(context.Context, *ListCardsRequest) (*ListCardsResponse, error)
	ListSets(context.Context, *ListSetsRequest) (*ListSetsResponse, error)
	mustEmbedUnimplementedMTGRPCServer()
}

// UnimplementedMTGRPCServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMTGRPCServer struct{}

func (UnimplementedMTGRPCServer) GetCard(context.Context, *GetCardRequest) (*GetCardResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCard not implemented")
}
func (UnimplementedMTGRPCServer) SearchCards(context.Context, *SearchCardsRequest) (*SearchCardsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchCards not implemented")
}
func (UnimplementedMTGRPCServer) ListCards(context.Context, *ListCardsRequest) (*ListCardsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListCards not implemented")
}
func (UnimplementedMTGRPCServer) ListSets(context.Context, *ListSetsRequest) (*ListSetsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSets not implemented")
}
func (UnimplementedMTGRPCServer) mustEmbedUnimplementedMTGRPCServer() {}
func (UnimplementedMTGRPCServer) testEmbeddedByValue()                {}

// UnsafeMTGRPCServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MTGRPCServer will
// result in compilation errors.
type UnsafeMTGRPCServer interface {
	mustEmbedUnimplementedMTGRPCServer()
}

func RegisterMTGRPCServer(s grpc.ServiceRegistrar, srv MTGRPCServer) {
	// If the following call panics, it indicates UnimplementedMTGRPCServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MTGRPC_ServiceDesc, srv)
}

func _MTGRPC_GetCard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MTGRPCServer).GetCard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MTGRPC_GetCard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MTGRPCServer).GetCard(ctx, req.(*GetCardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MTGRPC_SearchCards_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchCardsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MTGRPCServer).SearchCards(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MTGRPC_SearchCards_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MTGRPCServer).SearchCards(ctx, req.(*SearchCardsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MTGRPC_ListCards_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCardsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MTGRPCServer).ListCards(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MTGRPC_ListCards_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MTGRPCServer).ListCards(ctx, req.(*ListCardsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MTGRPC_ListSets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSetsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MTGRPCServer).ListSets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MTGRPC_ListSets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MTGRPCServer).ListSets(ctx, req.(*ListSetsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MTGRPC_ServiceDesc is the grpc.ServiceDesc for MTGRPC service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MTGRPC_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cards.MTGRPC",
	HandlerType: (*MTGRPCServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCard",
			Handler:    _MTGRPC_GetCard_Handler,
		},
		{
			MethodName: "SearchCards",
			Handler:    _MTGRPC_SearchCards_Handler,
		},
		{
			MethodName: "ListCards",
			Handler:    _MTGRPC_ListCards_Handler,
		},
		{
			MethodName: "ListSets",
			Handler:    _MTGRPC_ListSets_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/cards.proto",
}
